export const UPDATE_WORKSPACE_HOSTNAME = 'UPDATE_WORKSPACE_HOSTNAME';
export const ADD_WORKSPACE = 'ADD_WORKSPACE';

export const SET_WORKSPACE_INFO = 'SET_WORKSPACE_INFO';
export const SET_WORKSPACE_STATUS = 'SET_WORKSPACE_STATUS';
export const SET_WORKSPACE_ERROR_MESSAGE = 'SET_WORKSPACE_ERROR_MESSAGE';

export const GET_AVAILABLE_ROOMS = 'GET_AVAILABLE_ROOMS';
export const SET_AVAILABLE_ROOMS = 'SET_AVAILABLE_ROOMS';
export const SET_AVAILABLE_ROOMS_STATUS = 'SET_AVAILABLE_ROOMS_STATUS';
export const SET_AVAILABLE_ROOMS_ERROR_MESSAGE = 'SET_AVAILABLE_ROOMS_ERROR_MESSAGE';

export const FILTER_ROOMS_BY_NAME = 'FILTER_ROOMS_BY_NAME';
export const FILTER_ROOMS_BY_NEXT_HOUR_AVAILABILITY = 'FILTER_ROOMS_BY_NEXT_HOUR_AVAILABILITY';

export const INIT_BOOKING = 'INIT_BOOKING';
export const CANCEL_BOOKING = 'CANCEL_BOOKING';
export const MAKE_BOOKING = 'MAKE_BOOKING';
export const FINISH_BOOKING = 'FINISH_BOOKING';
export const SET_BOOKING_STATUS = 'SET_BOOKING_STATUS';
export const SET_BOOKING_ERROR_MESSAGE = 'SET_BOOKING_ERROR_MESSAGE';

export const UPDATE_EVENT_FIELD = 'UPDATE_EVENT_FIELD';
export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const REMOVE_PARTICIPANT = 'REMOVE_PARTICIPANT';
export const SET_PARTICIPANT_INDEX_FOR_EDIT = 'SET_PARTICIPANT_INDEX_FOR_EDIT';

export const VALIDATE_BOOKING_TIME = 'VALIDATE_BOOKING_TIME';