export const ADD_WORKSPACE = 'ADD_WORKSPACE';

// export const GET_WORKSPACE_INFO = 'GET_WORKSPACE_INFO';
export const SET_WORKSPACE_INFO = 'SET_WORKSPACE_INFO';
export const SET_WORKSPACE_INFO_STATUS = 'SET_WORKSPACE_INFO_STATUS';

export const GET_AVAILABLE_ROOMS = 'GET_AVAILABLE_ROOMS';
export const SET_AVAILABLE_ROOMS = 'SET_AVAILABLE_ROOMS';
export const SET_AVAILABLE_ROOMS_STATUS = 'SET_AVAILABLE_ROOMS_STATUS';